#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate a LaTeX "big table" for probe results:
rows = (model, language), columns = task families.

It parses each task family's `plot_results.py` to stay consistent with the
experiment mapping used for visualization.

Output (default):
  - src/probe/latex_tables/probe_big_table.tex
"""

from __future__ import annotations

import argparse
import ast
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


REPO_ROOT = Path(__file__).resolve().parents[2]
PROBE_DIR = REPO_ROOT / "src" / "probe"


TASK_FAMILIES = {
    "task_family_1": "Task 1 (Relation)",
    "task_family_2": "Task 2 (Orientation)",
    "task_family_3": "Task 3 (Procedure)",
}

LANG_ORDER = ["English", "Chinese", "Arabic"]


@dataclass(frozen=True)
class BestMetrics:
    r2: float
    best_layer: int
    mae: Optional[float] = None
    rmse: Optional[float] = None


def _latex_escape(s: str) -> str:
    # Minimal escapes for model names / captions.
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("~", "\\textasciitilde{}")
        .replace("^", "\\textasciicircum{}")
    )


def parse_experiments_dict(plot_results_py: Path) -> Dict[str, Dict[str, str]]:
    """
    Parse `experiments = {...}` from a plot_results.py using AST + literal_eval.
    """
    tree = ast.parse(plot_results_py.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "experiments":
                    return ast.literal_eval(node.value)  # type: ignore[arg-type]
    raise ValueError(f"Could not find `experiments = ...` in {plot_results_py}")


def load_best_metrics(result_json_path: Path) -> BestMetrics:
    raw = json.loads(result_json_path.read_text(encoding="utf-8"))

    layer_r2 = raw["layer_r2"]
    if "best_layer" in raw:
        best_layer = int(raw["best_layer"])
    else:
        best_layer = int(max(range(len(layer_r2)), key=lambda i: layer_r2[i]))

    best_r2 = float(layer_r2[best_layer])

    mae = None
    rmse = None
    if "best_layer_metrics" in raw and isinstance(raw["best_layer_metrics"], dict):
        blm: Dict[str, Any] = raw["best_layer_metrics"]
        mae = float(blm["mae"]) if "mae" in blm else None
        rmse = float(blm["rmse"]) if "rmse" in blm else None
    else:
        if "layer_mae" in raw:
            mae = float(raw["layer_mae"][best_layer])
        if "layer_rmse" in raw:
            rmse = float(raw["layer_rmse"][best_layer])

    return BestMetrics(r2=best_r2, best_layer=best_layer, mae=mae, rmse=rmse)


def format_cell(metrics: Optional[BestMetrics], include_errors: bool) -> str:
    if metrics is None:
        return "--"
    lines = [f"R$^2$={metrics.r2:.3f}", f"L={metrics.best_layer}"]
    if include_errors:
        if metrics.mae is not None:
            lines.append(f"MAE={metrics.mae:.3f}")
        if metrics.rmse is not None:
            lines.append(f"RMSE={metrics.rmse:.3f}")
    return "\\makecell{" + r"\\ ".join(lines) + "}"


def build_table(
    include_errors: bool = True,
    caption: str = "Probe best-layer metrics by model, language, and task family.",
    label: str = "tab:probe_big_table",
) -> str:
    experiments_by_family: Dict[str, Dict[str, Dict[str, str]]] = {}
    for family in TASK_FAMILIES.keys():
        plot_py = PROBE_DIR / family / "plot_results.py"
        experiments_by_family[family] = parse_experiments_dict(plot_py)

    model_order: list[str] = []
    seen = set()
    for family in TASK_FAMILIES.keys():
        for m in experiments_by_family[family].keys():
            if m not in seen:
                model_order.append(m)
                seen.add(m)

    metrics: Dict[Tuple[str, str, str], Optional[BestMetrics]] = {}
    for family in TASK_FAMILIES.keys():
        base_dir = PROBE_DIR / family
        exp = experiments_by_family[family]
        for model, langs in exp.items():
            for lang, filename in langs.items():
                p = base_dir / filename
                metrics[(family, model, lang)] = load_best_metrics(p) if p.exists() else None

    headers = ["Model", "Language"] + [TASK_FAMILIES[f] for f in TASK_FAMILIES.keys()]
    col_spec = "ll" + ("c" * len(TASK_FAMILIES))

    lines: list[str] = []
    lines.append("% Auto-generated by src/probe/generate_probe_big_table.py")
    lines.append("% Requires: \\usepackage{booktabs,adjustbox,makecell}")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.2}")
    lines.append("\\begin{adjustbox}{max width=\\textwidth}")
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    lines.append("\\toprule")
    lines.append(" & ".join(headers) + r" \\")
    lines.append("\\midrule")

    for model in model_order:
        for lang in LANG_ORDER:
            row = [_latex_escape(model), _latex_escape(lang)]
            for family in TASK_FAMILIES.keys():
                row.append(format_cell(metrics.get((family, model, lang)), include_errors=include_errors))
            lines.append(" & ".join(row) + r" \\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{adjustbox}")
    lines.append(f"\\caption{{{_latex_escape(caption)}}}")
    lines.append(f"\\label{{{_latex_escape(label)}}}")
    lines.append("\\end{table*}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out",
        type=str,
        default=str(PROBE_DIR / "latex_tables" / "probe_big_table.tex"),
        help="Output .tex path",
    )
    ap.add_argument(
        "--no-errors",
        action="store_true",
        help="Do not include MAE/RMSE lines in cells (R^2 + best layer only).",
    )
    ap.add_argument("--caption", type=str, default="Probe best-layer metrics by model, language, and task family.")
    ap.add_argument("--label", type=str, default="tab:probe_big_table")
    args = ap.parse_args()

    out_path = Path(args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    tex = build_table(include_errors=not args.no_errors, caption=args.caption, label=args.label)
    out_path.write_text(tex, encoding="utf-8")
    print(f"Wrote LaTeX table to: {out_path}")


if __name__ == "__main__":
    main()





