Loading from local path: /home/s202507009/workspace/LLMs/Qwen2.5/Qwen2.5-7B-Instruct
Converting to HookedTransformer...
Loaded pretrained model Qwen/Qwen2.5-7B-Instruct into HookedTransformer

===== Model Config =====
HookedTransformerConfig:
{'NTK_by_parts_factor': 8.0,
 'NTK_by_parts_high_freq_factor': 4.0,
 'NTK_by_parts_low_freq_factor': 1.0,
 'NTK_original_ctx_len': 8192,
 'act_fn': 'silu',
 'attention_dir': 'causal',
 'attn_only': False,
 'attn_scale': 11.313708498984761,
 'attn_scores_soft_cap': -1.0,
 'attn_types': None,
 'checkpoint_index': None,
 'checkpoint_label_type': None,
 'checkpoint_value': None,
 'd_head': 128,
 'd_mlp': 18944,
 'd_model': 3584,
 'd_vocab': 152064,
 'd_vocab_out': 152064,
 'decoder_start_token_id': None,
 'default_prepend_bos': False,
 'device': 'cuda:0',
 'dtype': torch.float16,
 'eps': 1e-06,
 'experts_per_token': None,
 'final_rms': True,
 'from_checkpoint': False,
 'gated_mlp': True,
 'init_mode': 'gpt2',
 'init_weights': False,
 'initializer_range': 0.02,
 'load_in_4bit': False,
 'model_name': 'Qwen2.5-7B-Instruct',
 'n_ctx': 2048,
 'n_devices': 1,
 'n_heads': 28,
 'n_key_value_heads': 4,
 'n_layers': 28,
 'n_params': 7141851136,
 'normalization_type': 'RMS',
 'num_experts': None,
 'original_architecture': 'Qwen2ForCausalLM',
 'output_logits_soft_cap': -1.0,
 'parallel_attn_mlp': False,
 'positional_embedding_type': 'rotary',
 'post_embedding_ln': False,
 'relative_attention_max_distance': None,
 'relative_attention_num_buckets': None,
 'rotary_adjacent_pairs': False,
 'rotary_base': 1000000.0,
 'rotary_dim': 128,
 'scale_attn_by_inverse_layer_idx': False,
 'seed': None,
 'tie_word_embeddings': False,
 'tokenizer_name': 'Qwen/Qwen2.5-7B-Instruct',
 'tokenizer_prepends_bos': False,
 'trust_remote_code': False,
 'ungroup_grouped_query_attention': False,
 'use_NTK_by_parts_rope': False,
 'use_attn_in': False,
 'use_attn_result': False,
 'use_attn_scale': True,
 'use_hook_mlp_in': False,
 'use_hook_tokens': False,
 'use_local_attn': False,
 'use_normalization_before_and_after': False,
 'use_qk_norm': False,
 'use_split_qkv_input': False,
 'window_size': None}

===== Key Fields =====
n_layers: 28
d_model: 3584
n_heads: 28
d_mlp: 18944
