#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate a LaTeX "big table" for data generation accuracy results:
rows = (model, language), columns = task families.

This script reads accuracy_analysis_*_test.json files from each task family's
data directory to create a comprehensive accuracy comparison table.

Output (default):
  - src/data_generation/latex_tables/accuracy_big_table.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple


REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_GEN_DIR = REPO_ROOT / "src" / "data_generation"


TASK_FAMILIES = {
    "task_family_1": {
        "name": "Task 1 (Relation)",
        "data_dir": "data_relation",
    },
    "task_family_2": {
        "name": "Task 2 (Orientation)",
        "data_dir": "data_orientation",
    },
    "task_family_3": {
        "name": "Task 3 (Procedure)",
        "data_dir": "data_procedure",
    },
}

# Language mapping
LANG_MAP = {
    "EN": "English",
    "CN": "Chinese",
    "AR": "Arabic",
}

LANG_ORDER = ["English", "Chinese", "Arabic"]

# Models to include (can be extended when more models are added)
MODELS = [
    "Qwen2.5-7B-Instruct",
]


@dataclass(frozen=True)
class AccuracyMetrics:
    """Store accuracy metrics for a single experiment."""
    total: int
    correct: int
    accuracy: float


def _latex_escape(s: str) -> str:
    """Escape special LaTeX characters."""
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("~", "\\textasciitilde{}")
        .replace("^", "\\textasciicircum{}")
    )


def load_accuracy_metrics(json_path: Path) -> Optional[AccuracyMetrics]:
    """Load overall accuracy metrics from an accuracy_analysis JSON file."""
    if not json_path.exists():
        return None
    
    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
        overall = data.get("overall", {})
        
        return AccuracyMetrics(
            total=int(overall.get("total", 0)),
            correct=int(overall.get("correct", 0)),
            accuracy=float(overall.get("accuracy", 0.0)),
        )
    except Exception as e:
        print(f"Warning: Failed to load {json_path}: {e}")
        return None


def format_cell(metrics: Optional[AccuracyMetrics], include_details: bool) -> str:
    """Format a table cell with accuracy metrics."""
    if metrics is None:
        return "--"
    
    lines = [f"{metrics.accuracy:.1f}\\%"]
    
    if include_details:
        lines.append(f"({metrics.correct}/{metrics.total})")
    
    if len(lines) > 1:
        return "\\makecell{" + r"\\ ".join(lines) + "}"
    else:
        return lines[0]


def build_table(
    include_details: bool = True,
    caption: str = "Accuracy (\\%) of models on different task families across languages.",
    label: str = "tab:accuracy_big_table",
) -> str:
    """Build the LaTeX table."""
    
    # Load all metrics
    metrics: Dict[Tuple[str, str, str], Optional[AccuracyMetrics]] = {}
    
    for family_key, family_info in TASK_FAMILIES.items():
        data_dir = DATA_GEN_DIR / family_key / family_info["data_dir"]
        
        for model in MODELS:
            for lang_code, lang_name in LANG_MAP.items():
                # Build path to accuracy_analysis file
                json_file = data_dir / f"accuracy_analysis_{lang_code}_test.json"
                metrics[(model, lang_name, family_key)] = load_accuracy_metrics(json_file)
    
    # Build table structure
    headers = ["Model", "Language"] + [info["name"] for info in TASK_FAMILIES.values()]
    col_spec = "ll" + ("c" * len(TASK_FAMILIES))
    
    lines: list[str] = []
    lines.append("% Auto-generated by src/data_generation/generate_accuracy_big_table.py")
    lines.append("% Requires: \\usepackage{booktabs,adjustbox,makecell}")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.3}")
    lines.append("\\begin{adjustbox}{max width=\\textwidth}")
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    lines.append("\\toprule")
    lines.append(" & ".join(headers) + r" \\")
    lines.append("\\midrule")
    
    for model in MODELS:
        for lang in LANG_ORDER:
            row = [_latex_escape(model), _latex_escape(lang)]
            for family_key in TASK_FAMILIES.keys():
                metric = metrics.get((model, lang, family_key))
                row.append(format_cell(metric, include_details=include_details))
            lines.append(" & ".join(row) + r" \\")
    
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{adjustbox}")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{label}}}")
    lines.append("\\end{table*}")
    lines.append("")
    
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate a LaTeX table of accuracy results for all task families."
    )
    ap.add_argument(
        "--out",
        type=str,
        default=str(DATA_GEN_DIR / "latex_tables" / "accuracy_big_table.tex"),
        help="Output .tex path",
    )
    ap.add_argument(
        "--no-details",
        action="store_true",
        help="Do not include (correct/total) details in cells (accuracy only).",
    )
    ap.add_argument(
        "--caption",
        type=str,
        default="Accuracy (\\%) of models on different task families across languages.",
    )
    ap.add_argument("--label", type=str, default="tab:accuracy_big_table")
    args = ap.parse_args()
    
    out_path = Path(args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    tex = build_table(
        include_details=not args.no_details,
        caption=args.caption,
        label=args.label,
    )
    out_path.write_text(tex, encoding="utf-8")
    print(f"✓ Wrote LaTeX table to: {out_path}")


if __name__ == "__main__":
    main()




